### ISSUE TITLE
Error: Missing boost-zil.json in root dir $NODE_PATH/node_modules/boost-zil/lib/scripts

### ISSUE THREAD

**Issue by Giulio-Grassi** [MszBednarski/boost-zil#2]
[myProjectZil.zip](https://github.com/MszBednarski/boost-zil/files/8652052/myProjectZil.zip)
[Terminal Saved Output.zip](https://github.com/MszBednarski/boost-zil/files/8652083/Terminal.Saved.Output.zip)
NODE VERSION: 
nvm 14.19.1

even after a clean install of the package, following the examples outlined in the get started guide leads to the error
Error: Missing boost-zil.json in root dir $NODE_PATH/node_modules/boost-zil/lib/scripts

**Comment by MszBednarski** [comment]
# The following dockerfile works (which is what you gave me):
```dockerfile
FROM node:14.19.1

WORKDIR /app

RUN npm i boost-zil@latest --unsafe-perm -g
RUN boost-zil-project
# this works
RUN boost-zil-build
# this works
RUN yarn build
# this works
RUN npm run build
ENTRYPOINT cat /app/src/SmartContract/build/bind.ts
```
### You can build and run it with:
```bash
docker build -t problem . && docker run problem
```
## The output of the dockerfile is the following
```bash
<the contents of the bind.ts for smartcontract>
```
## Thus it is an issue with your project setup not boost-zil
# Note
- There was no updates to the package so how could it suddenly break across your usage?
- Next time make a repo not zip file
- Give more info
- If you want your problem fixed you need to prove that it is an issue with boost-zil not with your project
- The error clearly states that there is something wrong with your root directory
